spring.application.name=chess

#Redis
spring.data.redis.host = localhost
spring.data.redis.port = 6379

#Postgres
spring.datasource.url = jdbc:postgresql://localhost:5432/chessdb
spring.datasource.username = postgres
spring.datasource.password = Rahul

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
